// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWb6rTYLrH0cX5cpEmdLBqMTBpRwE7B-8',
    appId: '1:388130539888:web:6289f891aeb1bab66267b5',
    messagingSenderId: '388130539888',
    projectId: 'eps-client',
    authDomain: 'eps-client.firebaseapp.com',
    storageBucket: 'eps-client.firebasestorage.app',
    measurementId: 'G-QV0HJ02WXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQyg580Jo9pEYK9TqdoAV1eqZ34ertn0M',
    appId: '1:388130539888:android:00794003df8fbfa06267b5',
    messagingSenderId: '388130539888',
    projectId: 'eps-client',
    storageBucket: 'eps-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhdLQW3DpQu7DvV6L6Dp_c_Fcq9pNCRAs',
    appId: '1:388130539888:ios:ddb9995d5b4758c76267b5',
    messagingSenderId: '388130539888',
    projectId: 'eps-client',
    storageBucket: 'eps-client.firebasestorage.app',
    iosBundleId: 'com.example.epsClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhdLQW3DpQu7DvV6L6Dp_c_Fcq9pNCRAs',
    appId: '1:388130539888:ios:ddb9995d5b4758c76267b5',
    messagingSenderId: '388130539888',
    projectId: 'eps-client',
    storageBucket: 'eps-client.firebasestorage.app',
    iosBundleId: 'com.example.epsClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWb6rTYLrH0cX5cpEmdLBqMTBpRwE7B-8',
    appId: '1:388130539888:web:a9e1ab56c4458c646267b5',
    messagingSenderId: '388130539888',
    projectId: 'eps-client',
    authDomain: 'eps-client.firebaseapp.com',
    storageBucket: 'eps-client.firebasestorage.app',
    measurementId: 'G-6D4643SZ75',
  );
}
