// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFb5p9cAzCNEF2YQlp6hzLBfZS9SfP5Yo',
    appId: '1:568985103888:web:ef86c90a1be2471d1f2495',
    messagingSenderId: '568985103888',
    projectId: 'eps-c2a0b',
    authDomain: 'eps-c2a0b.firebaseapp.com',
    storageBucket: 'eps-c2a0b.firebasestorage.app',
    measurementId: 'G-B6B2492XGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW4U9n1Uit_Ri4W0uJ60kpPHpbUT4DODI',
    appId: '1:568985103888:android:22fd51c6ce4756171f2495',
    messagingSenderId: '568985103888',
    projectId: 'eps-c2a0b',
    storageBucket: 'eps-c2a0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDf2rKgM3iZ9uIGlpqv2UFVNiF0bh8T4',
    appId: '1:568985103888:ios:c39acf3ef80343d71f2495',
    messagingSenderId: '568985103888',
    projectId: 'eps-c2a0b',
    storageBucket: 'eps-c2a0b.firebasestorage.app',
    iosBundleId: 'com.example.epsClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmDf2rKgM3iZ9uIGlpqv2UFVNiF0bh8T4',
    appId: '1:568985103888:ios:c39acf3ef80343d71f2495',
    messagingSenderId: '568985103888',
    projectId: 'eps-c2a0b',
    storageBucket: 'eps-c2a0b.firebasestorage.app',
    iosBundleId: 'com.example.epsClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFb5p9cAzCNEF2YQlp6hzLBfZS9SfP5Yo',
    appId: '1:568985103888:web:98035c7e6f286e991f2495',
    messagingSenderId: '568985103888',
    projectId: 'eps-c2a0b',
    authDomain: 'eps-c2a0b.firebaseapp.com',
    storageBucket: 'eps-c2a0b.firebasestorage.app',
    measurementId: 'G-74RY7KFXFH',
  );
}
